name: livingdifferent
favicon: null
layout_spectrum: 0
typography_spectrum: 0.51121
title: livingdifferent
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#dfdfdf'
    - '#9d9d9d'
    - '#101010'
    - '#6c6c6c'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
