name: livingdifferent
favicon: null
layout_spectrum: 0.51982
typography_spectrum: 0.51121
title: livingdifferent
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#719ed5'
    - '#605e5d'
    - '#ad9275'
    - '#171316'
    - '#ebdcbf'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
