name: livingdifferent
favicon: null
layout_spectrum: 0.25603
typography_spectrum: 0.51121
title: livingdifferent
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a6a6a6'
    - '#5a5a5a'
    - '#c8c8c8'
    - '#323232'
    - '#fcfcfc'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
